service: api-v1-auth

provider:
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  tags:
    lumigo:auto-trace: true

custom:
  logRetentionInDays: 7
  prune:
    automatic: true
    number: 1

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention
  - serverless-prune-plugin

functions:
  helloReadWorld:
    handler: src/hello/handlers.getMessageHandler
    events:
      - http:
          path: hello
          method: get
          authorizer: 
            name: authorizerFunc
            scopes:
              - client-credentials-flow-demo/hello.read
  helloWriteWorld:
    handler: src/hello/handlers.createMessageHandler
    events:
      - http:
          path: hello
          method: post
          authorizer: 
            name: authorizerFunc
            scopes:
              - client-credentials-flow-demo/hello.write
  authorizerFunc:
    handler: src/authorizer/handler.default
    environment:
      USER_POOL_ID: !Ref ApiV1AuthUserPool

resources:
  - ${file(infrastructure/cognito.yml)}