service: api-v1-auth

provider:
  apiGateway:
    apiKeys:
      - IntegrationTestClient
    usagePlan:
      quota:
        limit: 5000
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  deploymentBucket:
    name: com.reference-architecture.deploys
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  tags:
    lumigo:auto-trace: true

custom:
  logRetentionInDays: 7
  prune:
    automatic: true
    number: 1

package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket
  - serverless-iam-roles-per-function
  - serverless-plugin-log-retention
  - serverless-prune-plugin

functions:
  helloWorld:
    handler: src/hello/handlers.getMessageHandler
    events:
      - http:
          path: hello
          method: get
          private: true
          authorizer: authorizerFunc
  authorizerFunc:
    handler: src/authorizer/handler.default
    environment:
      USER_POOL_ID: !Ref ApiV1AuthUserPool

resources:
  - ${file(infrastructure/cognito.yml)}